# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f34216a9bd8afadf9fc7cdc5034362435c0fd0767f228f2b00adac62c3aa99ca936636d2bfc8cfd87d0691e6f79bd7ac9777e6341753f783e8a57ec9859b972

test:
  secret_key_base: 21a5b6c02b6a9da7098fb7d1ead4ffff44b3d60b7049783a0e57379df8fc24d3cabcae656d341dbda19c17335e9bc2e52a4c833224f4ac6f17fc22add6ba48e2

# Do not keep production secrets in the repository,
production:
  secret_key_base: <%= File.read(Rails.root.join('config/secret.key')).strip %>

heroku:
  secret_key_base: <%= ENV['MIRROR_SECRET'] %>
